### PR TITLE
Extensions in readme

### PR DESCRIPTION
**Pull request by Richard-Weiss**
Adds the Firefox and Chrome extension links to the readme.
Also add some subheadings and a gitignore.

### CODE REVIEW

**Comment by lugia19** [comment]
I already have a .gitignore, as there are some other files I don't want to include.

The README changes are fine, though. Just remove the gitignore and I'll merge.

**Comment by Richard-Weiss** [comment]
I don't see a .gitignore in main, do you maybe just have it locally?

**Comment by lugia19** [comment]
Yeah, just didn't feel like including it. I guess I can do so later.

-------- Original Message --------

**Comment by Richard-Weiss** [comment]
You can just squash merge the PR, pull the changes locally to merge the gitignore and then include your changes in your next commit if you want.
Or just not include the commit for the gitignore I made if you want to only do it in your next commit.

**Pull request merged**
